### ISSUE TITLE
sfm issues

### ISSUE THREAD

**Issue by lgq-gpu** [zju3dv/OnePose_Plus_Plus#18]
Hello, thank you for sharing your code, I want to ask you a question, when I run the run.py file, I run to (match_worker_ray_wrapper pid=31722) Global seed set to 666 here, it keeps stuck, by the way my DeepLM is not installed successfully, please ask this question How to solve this problem?

>(oneposeplus) lgq@lgq-B560M-AORUS-PRO-AX:/mnt/500_disk/OnePose_Plus_Plus$ python run.py +preprocess=sfm_inference_lowtexture.yaml use_local_ray=True
run.py:398: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="configs/", config_name="config.yaml")
/home/lgq/anaconda3/envs/oneposeplus/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/lgq/anaconda3/envs/oneposeplus/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
2023-03-25 11:30:45.174 | INFO     | __main__:sfm:32 - Process all objects in directory:/mnt/500_disk/OnePose_Plus_Plus/data/datasets/lowtexture_test_data/lowtexture_test_data, process: 1 sequences
2023-03-25 11:30:45.176 | INFO     | __main__:sfm_worker:92 - Worker: 0 will process: ['0700', '0701', '0702', '0703', '0706', '0707', '0708', '0710', '0712', '0713', '0714', '0715', '0718', '0719', '0720', '0721', '0722', '0723', '0724', '0725', '0726', '0727', '0728', '0729', '0730', '0731', '0732', '0733', '0734', '0735', '0736', '0737', '0740', '0741', '0742', '0743', '0744', '0745', '0746', '0748'], total: 40 objects
  0%|                                                    | 0/40 [00:00<?, ?it/s]2023-03-25 11:30:45.177 | INFO     | __main__:sfm_worker:97 - Processing /mnt/500_disk/OnePose_Plus_Plus/data/datasets/lowtexture_test_data/lowtexture_test_data/0700-toyrobot-others toyrobot-1.
2023-03-25 11:30:47.499 | INFO     | __main__:sfm_core:193 - Keypoint-Free SfM coarse reconstruction begin...
                                                                               (match_worker_ray_wrapper pid=31640) Global seed set to 6660/965 [00:00<?, ?it/s]
(match_worker_ray_wrapper pid=31642) Global seed set to 666
(match_worker_ray_wrapper pid=31641) Global seed set to 666
(match_worker_ray_wrapper pid=31722) Global seed set to 666

**Comment by hxy-123** [comment]
Hi, please refer to this [issue](https://github.com/zju3dv/OnePose_Plus_Plus/issues/15#issuecomment-1483710450) to see whether my reply can solve your problem!

**Comment by lgq-gpu** [comment]
Thank you, thank you so much!

**Comment by lgq-gpu** [comment]
@hxy-123 Hi, I'd like to ask you the following, what is the difference in the result between use_local_ray=True and use_local_ray=False in the command, because now I'm stuck at 93% when matching image pairs with use_local_ray=True, but it works fine with use_local_ray=False.

**Comment by hxy-123** [comment]
> @hxy-123 Hi, I'd like to ask you the following, what is the difference in the result between use_local_ray=True and use_local_ray=False in the command, because now I'm stuck at 93% when matching image pairs with use_local_ray=True, but it works fine with use_local_ray=False.

We use `ray` for parallelized matching during SfM which will be faster. The results will be the same. Getting stuck during parallelized matching may be due to the CUDA OOM since we use four workers in a single GPU.

**Comment by lgq-gpu** [comment]
Thank you for your answer, you are the most prompt answer I have encountered, I wish you more high level papers

**Comment by lgq-gpu** [comment]
Hi, I'm sorry to ask, but did you encounter the problem of no model name BACore when installing DeepLM? How to solve this problem @hxy-123

**Comment by hxy-123** [comment]
> Hi, I'm sorry to ask, but did you encounter the problem of no model name BACore when installing DeepLM? How to solve this problem @hxy-123

Is DeepLM properly installed or can it be successfully imported? [Without DeepLM](https://github.com/zju3dv/OnePose_Plus_Plus/blob/db74befb2dc2dd41c4d647b194bd6432d3570423/src/KeypointFreeSfM/post_optimization/optimizer/optimizer.py#L205) you can still run our code with our first-order solver.

**Comment by lgq-gpu** [comment]
Thanks for your reply

**Comment by yeying256** [comment]
> Hello, thank you for sharing your code, I want to ask you a question, when I run the run.py file, I run to (match_worker_ray_wrapper pid=31722) Global seed set to 666 here, it keeps stuck, by the way my DeepLM is not installed successfully, please ask this question How to solve this problem?
> 
> > (oneposeplus) lgq@lgq-B560M-AORUS-PRO-AX:/mnt/500_disk/OnePose_Plus_Plus$ python run.py +preprocess=sfm_inference_lowtexture.yaml use_local_ray=True
> > run.py:398: UserWarning:
> > The version_base parameter is not specified.
> > Please specify a compatability version level, or None.
> > Will assume defaults for version 1.1
> > @hydra.main(config_path="configs/", config_name="config.yaml")
> > /home/lgq/anaconda3/envs/oneposeplus/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config.yaml': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
> > warnings.warn(msg, UserWarning)
> > /home/lgq/anaconda3/envs/oneposeplus/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
> > See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
> > ret = run_job(
> > 2023-03-25 11:30:45.174 | INFO     | **main**:sfm:32 - Process all objects in directory:/mnt/500_disk/OnePose_Plus_Plus/data/datasets/lowtexture_test_data/lowtexture_test_data, process: 1 sequences
> > 2023-03-25 11:30:45.176 | INFO     | **main**:sfm_worker:92 - Worker: 0 will process: ['0700', '0701', '0702', '0703', '0706', '0707', '0708', '0710', '0712', '0713', '0714', '0715', '0718', '0719', '0720', '0721', '0722', '0723', '0724', '0725', '0726', '0727', '0728', '0729', '0730', '0731', '0732', '0733', '0734', '0735', '0736', '0737', '0740', '0741', '0742', '0743', '0744', '0745', '0746', '0748'], total: 40 objects
> > 0%|                                                    | 0/40 [00:00<?, ?it/s]2023-03-25 11:30:45.177 | INFO     | **main**:sfm_worker:97 - Processing /mnt/500_disk/OnePose_Plus_Plus/data/datasets/lowtexture_test_data/lowtexture_test_data/0700-toyrobot-others toyrobot-1.
> > 2023-03-25 11:30:47.499 | INFO     | **main**:sfm_core:193 - Keypoint-Free SfM coarse reconstruction begin...
> > (match_worker_ray_wrapper pid=31640) Global seed set to 6660/965 [00:00<?, ?it/s]
> > (match_worker_ray_wrapper pid=31642) Global seed set to 666
> > (match_worker_ray_wrapper pid=31641) Global seed set to 666
> > (match_worker_ray_wrapper pid=31722) Global seed set to 666

here：
https://github.com/zju3dv/OnePose_Plus_Plus/issues/5#issuecomment-1409761534
my code has worked
