### ISSUE TITLE
DeepLM installation problems

### ISSUE THREAD

**Issue by lgq-gpu** [zju3dv/OnePose_Plus_Plus#19]
Sorry, first of all, I apologize, I misunderstood the question you answered in the morning, I was in the installation of DeepLM when the problem of no module name BACore appeared

**Comment by Knightbreeze** [comment]
Hello, may I ask if you have solved the problem of no module name BACore when installing DeepLM? I also encountered the same problem during the installation process, and there is no solution at present, please come for help.

**Comment by lgq-gpu** [comment]
Hello, I was able to install the environment for a bit to install properly, but I don't know if this will work for you
In the end I installed conda environment from
https://github.com/CompVis/stable-diffusion,
and then it magically worked.

**Comment by lgq-gpu** [comment]
@Knightbreeze

**Comment by Knightbreeze** [comment]
> Hello, I was able to install the environment for a bit to install properly, but I don't know if this will work for you In the end I installed conda environment from https://github.com/CompVis/stable-diffusion, and then it magically worked.

Thank you very much for your reply. I will try this method at once.

**Comment by dadwadw233** [comment]
(https://github.com/hjwdzh/DeepLM/issues/6#issuecomment-2012241889) @Knightbreeze
