### ISSUE TITLE
Onepose Cap issue

### ISSUE THREAD

**Issue by lgq-gpu** [zju3dv/OnePose_Plus_Plus#20]
Hi, I would like to ask Onepose Cap.app whether the bottom surface of the 3D box box along the z-axis is close to the detected plane or can be adjusted up and down when performing target annotation, so we can use it to decide whether to buy it or not, thank you.

**Comment by hxy-123** [comment]
Hi, the bottom of the 3D box is close to the plane. Multiple planes can be detected and you can choose the aim plane. We are preparing for the official release of the capture app and a tutorial will also be available. Stay tuned for updates!

**Comment by lgq-gpu** [comment]
Hi, I have another small question, if we want to predict the bucket of a truck toy, can we use Onepose Cap.app to make the dataset?

**Comment by lgq-gpu** [comment]
@hxy-123
