### ISSUE TITLE
Pretrained model link not working

### ISSUE THREAD

**Issue by jucamohedano** [zju3dv/OnePose_Plus_Plus#21]
Hi! Great work and thank you for sharing it!

I can't access the link to the pre-trained model. It seems like it has expired.

Thanks!

**Comment by hxy-123** [comment]
> Hi,
> 
> The link to the example data in `doc/demo.md` isn't working either. Would you be able to update that link too?
> 
> Thanks!

We have renewed the link and thanks again!

**Comment by jucamohedano** [comment]
Thank you for the quick action taken! :)

**Comment by monajalal** [comment]
@hxy-123 the issue is current again! Could you please fix it as well?
