### ISSUE TITLE
stuck on Matching image pairs...:  27%|██▋       | 12/45 [00:11<00:07,  4.67it/s]

### ISSUE THREAD

**Issue by zhirui-gao** [zju3dv/OnePose_Plus_Plus#28]
the code stuck on "Matching image pairs...:  27%|██▋       | 12/45 [00:11<00:07,  4.67it/s]"
repeated 4x across cluster

**Comment by hxy-123** [comment]
Hi, I think this may because CUDA OOM due to the parallel matching. You can turn off it by setting `use_local_ray=False`.
