### ISSUE TITLE
merge.py issue

### ISSUE THREAD

**Issue by lgq-gpu** [zju3dv/OnePose_Plus_Plus#30]
Hi, thanks for sharing such excellent work first, and I'd like to ask if the training requires running the merge.py script, which is used to merge the three videos we've captured for the same object, for example, merging the 8 corners of the box for the three objects into one annotations

**Comment by hxy-123** [comment]
Hi, to construct your own training data, multiple video sequences should be merged into a single coordinate system, which is further detailed in the OnePose paper. However, currently, we do not intend to open-source the merge code of training data construction.
