### ISSUE TITLE
Problem in downloading pretrained weights for LoFTR

### ISSUE THREAD

**Issue by AliBahri94** [zju3dv/OnePose_Plus_Plus#43]
Hi, 

Thank you for releasing your great code. 
I have got a problem in downloading pretrained weights for LoFTR. When I click on the **_pretrained models_**, I get this error:

"Sorry, this link has expired."

**Comment by hxy-123** [comment]
Hi, sorry for the late reply. The links of pre-trained weights as well as datasets are updated.
