### ISSUE TITLE
stuck on Global seed set to 666  

### ISSUE THREAD

**Issue by RiccardoMaistri** [zju3dv/OnePose_Plus_Plus#5]
![image](https://user-images.githubusercontent.com/98355991/215530869-b829e0a2-5066-4053-9ce8-a7a21104fe76.png)
Hi, I am trying to use the datasert provided as a test but I got stuck into this.
Any workaround?

Thanks in advance

**Comment by frogbam** [comment]
change ${REPO_ROOT}/weights to ${REPO_ROOT}/weight

**Comment by RiccardoMaistri** [comment]
> I fixed this error as follows. Change REPO_ROOT/weights to REPO_ROOT/weight

I change weights to weight but nothing changed, could you show me your working tree?

**Comment by monajalal** [comment]
@RiccardoMaistri  and @frogbam  could you please let me know where you did this change? I have the same exact problem.

**Comment by monajalal** [comment]
figured

```
(pytorch3d) mona@ard-gpu-01:~/OnePose_Plus_Plus$ vi README.md 
(pytorch3d) mona@ard-gpu-01:~/OnePose_Plus_Plus$ mkdir weight
(pytorch3d) mona@ard-gpu-01:~/OnePose_Plus_Plus$ mv ~/Downloads/LoFTR_wsize9.ckpt weight
(pytorch3d) mona@ard-gpu-01:~/OnePose_Plus_Plus$ mv ~/Downloads/OnePosePlus_model.ckpt weight/

```

**Comment by vaish1604** [comment]
I did the same thing but I am still stuck. 

![image](https://github.com/zju3dv/OnePose_Plus_Plus/assets/80941602/2f768f5f-4548-4e7c-beba-ea4040a7df96)

**Comment by yeying256** [comment]
> I fixed this error as follows. Change REPO_ROOT/weights to REPO_ROOT/weight

Thanks very much!!!! It worked!!!
