### ISSUE TITLE
Wrong use of DeepLM as second-order solver

### ISSUE THREAD

**Issue by iamNCJ** [zju3dv/OnePose_Plus_Plus#8]
Hi, I've run your demo pipeline code with the DeepLM second order solver in the keypoint-Free SfM stage, and found that in file `src/KeypointFreeSfM/post_optimization/optimizer/optimizer.py` [L213](https://github.com/zju3dv/OnePose_Plus_Plus/blob/9a8296d20364b1a77a775d85f471709058c9f421/src/KeypointFreeSfM/post_optimization/optimizer/optimizer.py#L213), the return value of `DeepLM.Solve` was assigned to `optimized_variables`. However, DeepLM does update of variables _**inplace**_, and the return value of the `Solve` method is actually the cost value. Removing this wrong assignment and directly use the original `variables` solved this problem.

```python
# Use DeepLM lib:
SecondOrderSolve(
    variables=variables,
    constants=constants,
    indices=indices,
    verbose=self.verbose,
    fn=partial(residual_format, **partial_paras),
)
optimized_variables = variables
```

**Comment by hxy-123** [comment]
Hi, thank you for reminding us! We have made some modifications to the DeepLM module on our end and forgot to update the corresponding interface in its public version. However, we have fixed the issue now. Thanks again!

**Comment by iamNCJ** [comment]
Cool, thank you for the fix!
